name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: install
        run: yarn install
      - name: install wrangler
        run: yarn global add wrangler
      - name: set env
        run: |
          echo "CF_EMAIL=${CF_EMAIL}" >> $GITHUB_ENV
          echo "CF_API_TOKEN=${CF_API_TOKEN}" >> $GITHUB_ENV
        env:
          CF_EMAIL: ${{secrets.CLOUDFLARE_EMAIL}}
          CF_API_TOKEN: ${{secrets.WRANGLER_API_KEY}}
      - name: publish
        run: yarn deploy
